MCU = atmega32u4
BOOTLOADER = caterina

SPLIT_KEYBOARD = yes
SPLIT_TRANSPORT = serial

RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
RGBLIGHT_ANIMATIONS = no
OLED_ENABLE = no
WPM_ENABLE = no
VIA_ENABLE = yes
VIAL_ENABLE = yes

CAPS_WORD_ENABLE = no
COMBO_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LAYER_LOCK_ENABLE = no
MAGIC_ENABLE = no
REPEAT_KEY_ENABLE = no
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = no

ifeq ($(KEY_LAYOUT),)
    OPT_DEFS += -DCORNE_LAYOUT_42
else ifeq ($(KEY_LAYOUT),42)
    OPT_DEFS += -DCORNE_LAYOUT_42
else ifeq ($(KEY_LAYOUT),36)
    OPT_DEFS += -DCORNE_LAYOUT_36
else
    $(error KEY_LAYOUT must be 42 or 36)
endif
